version: '3.7'

services:

  app:
    container_name: pismo
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "9090:9090"
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}
      WEB_PORT: ${WEB_PORT}
    volumes:
      - ./:/app

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pismo
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

#Volumes
volumes:
  dbdata:
    driver: local
